# Generated by Django 4.2.7 on 2025-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('base_currency', models.CharField(max_length=5)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
