# Generated by Django 4.2.7 on 2025-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_ratee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='base_currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='country_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='currency_code',
            field=models.CharField(max_length=10),
        ),
    ]
