# Generated by Django 5.2.4 on 2025-08-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendhawala',
            fields=[
                ('send_hawala_id', models.AutoField(primary_key=True, serialize=False)),
                ('hawala_number', models.IntegerField(unique=True)),
                ('sender_name', models.CharField(max_length=32)),
                ('receiver_name', models.CharField(max_length=32)),
                ('amount', models.FloatField()),
                ('rate_type', models.CharField(max_length=32)),
                ('receiver_location', models.CharField(max_length=64)),
                ('exchanger_location', models.CharField(max_length=64)),
                ('sender_phone', models.CharField(max_length=15, unique=True)),
                ('hawala_fee', models.FloatField(blank=True, null=True)),
                ('dates', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
