# Generated by Django 5.2.4 on 2025-08-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_sendhawala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendhawala',
            name='status',
            field=models.CharField(choices=[('succes', 'Succes'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
