# Generated by Django 5.2.4 on 2025-08-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_sendhawala_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarafProfile',
            fields=[
                ('saraf_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password_hash', models.CharField(editable=False, max_length=255)),
                ('license_no', models.CharField(max_length=64, unique=True)),
                ('saraf_address', models.CharField(max_length=255)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('about_us', models.TextField()),
                ('about_hawala', models.TextField(blank=True, null=True)),
                ('service', models.TextField(blank=True, null=True)),
                ('work_history', models.IntegerField()),
                ('support_currencies', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Saraf Profile',
                'verbose_name_plural': 'Saraf Profiles',
                'db_table': 'saraf_profile',
            },
        ),
    ]
