# Generated by Django 5.2.4 on 2025-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_sarafprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarafprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='saraf_photos/'),
        ),
    ]
