# Generated by Django 5.2.4 on 2025-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_sarafprofile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sarafprofile',
            old_name='photo',
            new_name='id_card_back_photo',
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='id_card_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to='saraf_photos/'),
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='saraf_photos/'),
        ),
    ]
