# Generated by Django 5.2.4 on 2025-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_rename_photo_sarafprofile_id_card_back_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='normal_user_Profile',
            fields=[
                ('normal_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password_hash', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Normal User Profile',
                'verbose_name_plural': 'Normal User Profiles',
                'db_table': 'normal_user_profile',
            },
        ),
    ]
