# Generated by Django 5.2.4 on 2025-08-16 14:16

import Core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_normal_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR, GBP)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='Full currency name (e.g., US Dollar, Euro)', max_length=50)),
                ('symbol', models.CharField(help_text='Currency symbol (e.g., $, €, £)', max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is available for use')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate relative to base currency', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Province name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Province code', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this province is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'province',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='sarafprofile',
            name='support_currencies',
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sendhawala',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sendhawala',
            name='hawala_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='normal_user_profile',
            name='preferred_currency',
            field=models.ForeignKey(blank=True, help_text="User's preferred currency for transactions", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.currency'),
        ),
        migrations.AddField(
            model_name='sendhawala',
            name='currency',
            field=models.ForeignKey(default=Core.models.Currency.get_default_currency, on_delete=django.db.models.deletion.PROTECT, to='Core.currency'),
        ),
        migrations.AddField(
            model_name='sendhawala',
            name='hawala_fee_currency',
            field=models.ForeignKey(default=Core.models.Currency.get_default_currency, on_delete=django.db.models.deletion.PROTECT, related_name='hawala_fees', to='Core.currency'),
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Province where the Saraf operates', null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.province'),
        ),
        migrations.CreateModel(
            name='SupportedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('custom_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Custom exchange rate for this saraf', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_sarafs', to='Core.currency')),
                ('saraf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_currencies', to='Core.sarafprofile')),
            ],
            options={
                'verbose_name': 'Supported Currency',
                'verbose_name_plural': 'Supported Currencies',
                'db_table': 'supported_currency',
                'unique_together': {('saraf', 'currency')},
            },
        ),
    ]
