# Generated by Django 5.2.4 on 2025-08-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_add_currency_province_and_address_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarafprofile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='sarafprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sarafprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='sarafprofile',
            name='street_address',
        ),
        migrations.AlterField(
            model_name='sendhawala',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.currency'),
        ),
        migrations.AlterField(
            model_name='sendhawala',
            name='hawala_fee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hawala_fees', to='Core.currency'),
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
