# Generated by Django 5.2.4 on 2025-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_sarafprofile_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarafprofile',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sarafprofile',
            name='work_history',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
