# Generated by Django 5.2.4 on 2025-08-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0016_add_gbp_bhd_omr_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='sarafprofile',
            name='exchange_name',
            field=models.CharField(blank=True, help_text='Registered exchange business name', max_length=128, null=True),
        ),
    ]
