# Generated by Django 5.2.4 on 2025-08-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_province_sarafprofile_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarafprofile',
            name='province',
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='provinces',
            field=models.ManyToManyField(blank=True, related_name='sarafs', to='Core.province'),
        ),
    ]
