# Generated by Django 5.2.4 on 2025-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_remove_sarafprofile_province_sarafprofile_provinces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='sarafprofile',
            name='service',
        ),
        migrations.AddField(
            model_name='sarafprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='sarafs', to='Core.service'),
        ),
    ]
