# Generated by Django 5.2.4 on 2025-08-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_service_remove_sarafprofile_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['saraf_id', 'title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='sarafprofile',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='saraf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Core.sarafprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('saraf', 'title')},
        ),
    ]
