# Generated by Django 5.2.4 on 2025-08-21 04:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_alter_service_options_remove_sarafprofile_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user_profile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'Phone must be 10 digits and start with 0')]),
        ),
        migrations.AlterField(
            model_name='sarafprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'Phone must be 10 digits and start with 0')]),
        ),
        migrations.AlterField(
            model_name='sendhawala',
            name='sender_phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'Phone must be 10 digits and start with 0')]),
        ),
        migrations.CreateModel(
            name='SarafBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saraf_balances', to='Core.currency')),
                ('saraf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='Core.sarafprofile')),
            ],
            options={
                'verbose_name': 'Saraf Balance',
                'verbose_name_plural': 'Saraf Balances',
                'db_table': 'saraf_balance',
                'unique_together': {('saraf', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='SarafBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('loan_given', 'Loan Given'), ('borrow_received', 'Borrow Received')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('undeliver', 'Undeliver')], default='delivered', max_length=16)),
                ('tx_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date/time of the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saraf_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Core.sarafbalance')),
            ],
            options={
                'verbose_name': 'Saraf Balance Transaction',
                'verbose_name_plural': 'Saraf Balance Transactions',
                'db_table': 'saraf_balance_tx',
                'ordering': ['-created_at'],
            },
        ),
    ]
