# Generated by Django 5.2.4 on 2025-08-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_alter_normal_user_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarafbalancetransaction',
            name='tx_type',
            field=models.CharField(choices=[('loan_given', 'Loan Given'), ('borrow_received', 'Borrow Received'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=32),
        ),
    ]
