# Generated by Django 4.2.7 on 2025-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_alter_sarafbalancetransaction_tx_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Whether this is a popular currency'),
        ),
    ]
