# Generated by Django 4.2.7 on 2025-08-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_currency_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate relative to base currency', max_digits=15),
        ),
    ]
