# Generated by Django 4.2.7 on 2025-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_alter_currency_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_english',
            field=models.CharField(blank=True, help_text='English currency name', max_length=50),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_farsi',
            field=models.CharField(blank=True, help_text='Farsi currency name', max_length=50),
        ),
    ]
