# Generated by Django 4.2.7 on 2025-08-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_currency_name_english_currency_name_farsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendhawala',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('started', 'Started'), ('finished', 'Finished')], default='draft', max_length=10),
        ),
    ]
