# Generated by Django 4.2.7 on 2025-08-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_alter_sendhawala_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendhawala',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('started', 'Started'), ('snoozed', 'Snoozed')], default='draft', max_length=10),
        ),
    ]
