# Generated by Django 4.2.7 on 2025-08-24 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_alter_sendhawala_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveHawala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawala_number', models.CharField(default='', help_text='Hawala transaction number', max_length=20)),
                ('sender_name', models.CharField(default='', help_text='Name of the sender', max_length=100)),
                ('receiver_name', models.CharField(default='', help_text='Name of the receiver', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Transaction amount', max_digits=15)),
                ('rate_type', models.CharField(choices=[('buying', 'Buying Rate'), ('selling', 'Selling Rate'), ('middle', 'Middle Rate')], default='middle', help_text='Exchange rate type used', max_length=20)),
                ('sender_phone', models.CharField(default='', help_text="Sender's phone number", max_length=15)),
                ('hawala_fee', models.DecimalField(decimal_places=2, default=0, help_text='Transaction fee', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('started', 'Started'), ('snoozed', 'Snoozed')], default='draft', help_text='Transaction status', max_length=20)),
                ('dates', models.DateTimeField(help_text='Transaction date', null=True)),
                ('receiver_phone', models.CharField(help_text="Receiver's phone number", max_length=15)),
                ('receiver_id_card_photo', models.ImageField(blank=True, help_text="Photo of receiver's ID card", null=True, upload_to='receiver_photos/')),
                ('receiver_finger_photo', models.ImageField(blank=True, help_text="Photo of receiver's fingerprint", null=True, upload_to='receiver_photos/')),
                ('receiver_address', models.TextField(help_text="Receiver's physical address")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(help_text='Transaction currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.currency')),
                ('exchanger_location', models.ForeignKey(help_text="Exchanger's location", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receive_hawala_exchanger_location', to='Core.province')),
                ('hawala_fee_currency', models.ForeignKey(help_text='Currency for the transaction fee', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receive_hawala_fee_currency', to='Core.currency')),
                ('receiver_location', models.ForeignKey(help_text="Receiver's location", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receive_hawala_receiver_location', to='Core.province')),
                ('sendhawala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receive_hawala', to='Core.sendhawala')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Saraf who verified the receiver', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.sarafprofile')),
            ],
            options={
                'verbose_name': 'Receive Hawala',
                'verbose_name_plural': 'Receive Hawalas',
                'db_table': 'core_receive_hawala',
            },
        ),
    ]
