# Generated by Django 4.2.7 on 2025-08-24 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_receivehawala'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Unique customer account number', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('phone', models.CharField(blank=True, help_text="Customer's phone number", max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'Phone must be 10 digits and start with 0')])),
                ('address', models.TextField(blank=True, help_text="Customer's address", null=True)),
                ('job', models.CharField(blank=True, help_text="Customer's job/occupation", max_length=100, null=True)),
                ('finger_photo', models.ImageField(blank=True, help_text="Customer's fingerprint photo", null=True, upload_to='customer_photos/')),
                ('photo', models.ImageField(blank=True, help_text="Customer's photo", null=True, upload_to='customer_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('saraf', models.ForeignKey(help_text='Saraf who manages this customer account', on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='Core.sarafprofile')),
            ],
            options={
                'verbose_name': 'Customer Account',
                'verbose_name_plural': 'Customer Accounts',
                'db_table': 'customer_account',
                'unique_together': {('saraf', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('loan_given', 'Loan Given'), ('borrowed_from', 'Borrowed From'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Core.customeraccount')),
            ],
            options={
                'verbose_name': 'Customer Transaction',
                'verbose_name_plural': 'Customer Transactions',
                'db_table': 'customer_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='Core.customeraccount')),
            ],
            options={
                'verbose_name': 'Customer Balance',
                'verbose_name_plural': 'Customer Balances',
                'db_table': 'customer_balance',
                'unique_together': {('customer', 'currency')},
            },
        ),
    ]
