# Generated by Django 4.2.7 on 2025-08-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_customeraccount_customertransaction_customerbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Customer's current balance", max_digits=15),
        ),
    ]
