# Generated by Django 4.2.7 on 2025-08-25 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_message_alter_customertransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendhawala',
            name='sender_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'Phone must be 10 digits and start with 0')]),
        ),
    ]
