# Generated by Django 4.2.7 on 2025-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_alter_sendhawala_sender_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendhawala',
            name='status',
            field=models.CharField(choices=[('finished', 'Finished'), ('started', 'Started'), ('snoozed', 'Snoozed')], default='finished', max_length=10),
        ),
    ]
