# Generated by Django 4.2.7 on 2025-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_alter_sendhawala_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
