# Generated by Django 4.2.7 on 2025-08-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_alter_customertransaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarafLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount', max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Interest rate percentage (e.g., 5.50 for 5.5%)', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted')], default='active', help_text='Current status of the loan', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Additional notes about the loan', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Expected repayment date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repaid_at', models.DateTimeField(blank=True, help_text='Date when loan was fully repaid', null=True)),
                ('borrower', models.ForeignKey(help_text='Saraf who received the loan', on_delete=django.db.models.deletion.CASCADE, related_name='loans_received', to='Core.sarafprofile')),
                ('currency', models.ForeignKey(help_text='Currency of the loan', on_delete=django.db.models.deletion.PROTECT, to='Core.currency')),
                ('lender', models.ForeignKey(help_text='Saraf who gave the loan', on_delete=django.db.models.deletion.CASCADE, related_name='loans_given', to='Core.sarafprofile')),
            ],
            options={
                'verbose_name': 'Saraf Loan',
                'verbose_name_plural': 'Saraf Loans',
                'db_table': 'saraf_loan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SarafColleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', help_text='Status of the colleague relationship', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colleague', models.ForeignKey(help_text='Saraf who received the colleague request', on_delete=django.db.models.deletion.CASCADE, related_name='colleague_requests_received', to='Core.sarafprofile')),
                ('requester', models.ForeignKey(help_text='Saraf who sent the colleague request', on_delete=django.db.models.deletion.CASCADE, related_name='colleague_requests_sent', to='Core.sarafprofile')),
            ],
            options={
                'verbose_name': 'Saraf Colleague',
                'verbose_name_plural': 'Saraf Colleagues',
                'db_table': 'saraf_colleague',
                'unique_together': {('requester', 'colleague')},
            },
        ),
    ]
