# Generated by Django 4.2.7 on 2025-08-25 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_sarafloan_sarafcolleague'),
    ]

    operations = [
        # Remove fields from SarafColleague
        migrations.RemoveField(
            model_name='sarafcolleague',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sarafcolleague',
            name='updated_at',
        ),
        
        # Remove fields from SarafLoan
        migrations.RemoveField(
            model_name='sarafloan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='sarafloan',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='sarafloan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sarafloan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sarafloan',
            name='repaid_at',
        ),
        
        # Modify SarafLoan status field
        migrations.AlterField(
            model_name='sarafloan',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('undelivered', 'Undelivered')], default='undelivered', help_text='Delivery status of the loan', max_length=15),
        ),
        
        # Add date field to SarafLoan
        migrations.AddField(
            model_name='sarafloan',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of the loan'),
            preserve_default=False,
        ),
        
        # Create CurrencyExchange model
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in from_currency', max_digits=18)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate (to_currency per from_currency)', max_digits=10)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('undelivered', 'Undelivered')], default='undelivered', help_text='Delivery status of the exchange', max_length=15)),
                ('description', models.TextField(blank=True, help_text='Additional notes about the exchange', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date of the exchange')),
                ('exchanger', models.ForeignKey(help_text='Saraf who initiated the exchange', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_made', to='Core.sarafprofile')),
                ('from_currency', models.ForeignKey(help_text='Currency being exchanged from', on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_from', to='Core.currency')),
                ('receiver', models.ForeignKey(help_text='Saraf who received the exchange', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to='Core.sarafprofile')),
                ('to_currency', models.ForeignKey(help_text='Currency being exchanged to', on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_to', to='Core.currency')),
            ],
            options={
                'verbose_name': 'Currency Exchange',
                'verbose_name_plural': 'Currency Exchanges',
                'db_table': 'currency_exchange',
                'ordering': ['-date'],
            },
        ),
    ]
