# Generated by Django 4.2.7 on 2025-08-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0038_sarafcolleague_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sarafloan',
            options={'ordering': ['-date'], 'verbose_name': 'Saraf Loan', 'verbose_name_plural': 'Saraf Loans'},
        ),
        migrations.AlterField(
            model_name='sarafcolleague',
            name='colleague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleague_requests_received', to='Core.sarafprofile'),
        ),
        migrations.AlterField(
            model_name='sarafcolleague',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleague_requests_sent', to='Core.sarafprofile'),
        ),
        migrations.AlterModelTable(
            name='sarafcolleague',
            table=None,
        ),
    ]
