# Generated by Django 4.2.7 on 2025-08-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0039_alter_sarafloan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sarafbalancetransaction',
            name='saraf_balance',
        ),
        migrations.DeleteModel(
            name='SarafBalance',
        ),
        migrations.DeleteModel(
            name='SarafBalanceTransaction',
        ),
    ]
