# Generated by Django 4.2.7 on 2025-08-28 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0040_remove_sarafbalancetransaction_saraf_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivehawala',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='sendhawala',
            name='rate_type',
        ),
    ]
