# Generated by Django 4.2.7 on 2025-08-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0041_remove_receivehawala_rate_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendhawala',
            old_name='dates',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='sendhawala',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
