# Generated by Django 4.2.7 on 2025-08-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0042_rename_dates_sendhawala_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_user_profile',
            name='user_logo',
            field=models.ImageField(blank=True, help_text="User's profile logo/avatar", null=True, upload_to='normal_user_photos/'),
        ),
        migrations.AddField(
            model_name='normal_user_profile',
            name='user_wallpaper',
            field=models.ImageField(blank=True, help_text="User's profile wallpaper/background image", null=True, upload_to='normal_user_photos/'),
        ),
    ]
