# Generated by Django 4.2.7 on 2025-08-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0043_add_normal_user_logo_wallpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='SarafPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='saraf_photos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saraf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Core.sarafprofile')),
            ],
            options={
                'verbose_name': 'Saraf Post',
                'verbose_name_plural': 'Saraf Posts',
                'db_table': 'saraf_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
